blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.blog, name="blogs")
]

portfolioDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="home"),
    path('about/', views.about, name="about"),
    path('works/', include('works.urls')),
    path('blogs/', include('blog.urls')),
    path('home/', views.home, name="homeTwo")
]

handler404 = views.error_404
handler500 = views.error_500

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

works/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'works'

urlpatterns = [
    path('', views.index, name="workIndex"),
    path('<work_id>/', views.detail, name='workDetail')
]

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
	"""docstring for Blog"""
	title = models.CharField(max_length=250)
	link = models.TextField()
	content = models.TextField()
	datePub = models.CharField(max_length=250)

	def __str__(self):
		return self.title
		

works/models.py
from django.db import models

# Create your models here.

class WorkImage(models.Model):
	title = models.CharField(max_length=300)
	picture = models.FileField()

	def __str__(self):
		return self.title

class Works(models.Model):
	
	"""docstring for Works"""
	title = models.CharField(max_length=300)
	category = models.CharField(max_length=150)
	desc = models.TextField()
	tumbn = models.FileField()
	link = models.TextField()
	b_id = models.IntegerField()

	def __str__(self):
		return self.title



		

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Blog
import xml.etree.ElementTree as ET
import requests

# Create your views here.
def index(request):
    return render(request, 'blogs/index.html')

def blog(request):
	if Medium.get():
		context = {'blogs':Blog.objects.all()}

	return render(request, 'blogs/index.html', context)

class Medium:
	def get():
		Blog.objects.all().delete()
		r = requests.get('https://medium.com/feed/@keynekassapa13')
		xml = ET.fromstring(r.content)
		elements = xml[0][9:]
		for element in elements:
			blog = Blog()
			blog.title = element[0].text
			blog.link = element[1].text
			blog.content = element[-1].text
			blog.datePub = element.find('pubDate').text
			blog.save()
		return '200'

portfolioDjango/views.py
from django.http import HttpResponse
from django.shortcuts import render
import xml.etree.ElementTree as ET
import requests

def index(request):
    return render(request, 'index.html')

def about(request):
	return render(request, 'about.html')

def home(request):
	return render(request, 'home.html')

def error_404(request):
    data = {}
    return render(request,'404.html', data)

def error_500(request):
    data = {}
    return render(request,'404.html', data)

'''def blog(request):
	title, link = Medium.get()
	return render(request, 'blogs/index.html', {'link': link, 'title': title})

class Medium:
	def get():
		r = requests.get('https://medium.com/feed/@keynekassapa13')
		xml = ET.fromstring(r.content)
		elements = xml[0][9:]
		title = xml[0][9][0].text
		link = xml[0][9][1].text
		return title, link'''

works/views.py
from django.shortcuts import render
from django.views import generic
from .models import Works
import requests
import json

# Create your views here.
def index(request):
	if WorkClass.get():
		context = {'works':Works.objects.all()}

	return render(request, 'works/index.html', context)
	'''template_name = 'works/index.html'

	def get_queryset(self):
		return Works.objects.all().order_by('-pk')'''


def detail(request, work_id):
	url = 'http://www.behance.net/v2/projects/' + work_id + '?api_key=LSLLa7T268qpUueyWqDGJubMvW1xp0W6'
	r = requests.get(url)
	json_data = json.loads(r.text)
	workcat = str(json_data["project"]["fields"])[1:-1].replace("'","")
	workpic = json_data["project"]["modules"][0]["type"]
	if workpic == "image":
		workpic = json_data["project"]["modules"][0]["sizes"]["original"]
	else:
		workpic = json_data["project"]["covers"]["original"]

	context = {
	'workcat':workcat,
	'workname':json_data["project"]["name"],
	'workid':json_data["project"]["id"],
	'workurl':json_data["project"]["url"],
	'workpic':workpic,
	'workdes':json_data["project"]["description"]
	}
	return render(request, 'works/detail.html', context)

class WorkClass:
	def get():
		Works.objects.all().delete()
		r = requests.get('https://api.behance.net/v2/users/keynekassapa13/projects?client_id=LSLLa7T268qpUueyWqDGJubMvW1xp0W6')
		json_data = json.loads(r.text)
		for eachWork in json_data["projects"]:
			work = Works()
			work.title = eachWork["name"]
			work.category = str(eachWork["fields"])[1:-1].replace("'","")
			work.desc = ""
			work.tumbn = eachWork["covers"]["404"]
			work.link = eachWork["url"]
			work.b_id = eachWork["id"]
			work.save()
		return '200'

templates/about.html
{% extends "application.html" %}

{% block title %}About Me - Keyne Oei{% endblock %}

{% block content %}

{% load static %}

<style type="text/css">
	#footer-modif {
		position: fixed
	}
</style>
<link rel="stylesheet" type="text/css" href="{% static 'css/about.css' %}">
<div class="container">
	<h1 class="text-bold page-title">Keyne Kassapa Oei</h1>
	
	<div class="row">
		<div class="col-sm-6 box-text">
			
			See some of my work at

			<div class="row">
				<div class="col-6">
					<a href="http://www.behance.net/keynekassapa13" target="_blank"><i class="fab fa-behance-square"></i> Behance</a> 
					<br/><a href="https://www.linkedin.com/in/keynekassapa/" target="_blank"><i class="fab fa-medium"></i> Linkedin</a>
				</div>
				<div class="col-6">
					<a href="https://medium.com/@keynekassapa13/" target="_blank"><i class="fab fa-medium"></i> Medium</a>
					<br/><a href="http://instagram.com/keynekassapa13/"><i class="fab fa-instagram"></i> Instagram</a>
				</div>
			</div>
			
			
			<br/>Contact her
			<div class="row">
				<div class="col-6"><i class="fas fa-envelope"></i> <a href="href="mailto:keynekassapa13@gmail.com">keynekassapa13@gmail.com</a>
				</div>
				<div class="col-6"><i class="fas fa-mobile-alt"></i><a href="tel:0402-369-708"> 0402369708</a>
				</div>
			</div>
			<p><br/>Creative digital with 2+ years experience in digital design and web development. Experienced in delivering interfaces for websites and mostly acted as the front end developer.</p>
			<div>
				<img src="{% static 'images/key2.png' %}" class="profile-pic">
			</div>
			
		</div>

		<div class="col-sm-6 box-text">


			<h5 class="works-txt"> Work/Project Experience </h5> 

			<?xml version="1.0" encoding="utf-8"?>
			<!-- Generator: Adobe Illustrator 21.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
			<svg version="1.1" class="works" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="400"
				 viewBox="0 0 450 300" style="enable-background:new 0 0 450 317;" xml:space="preserve">
			<style type="text/css">
				.works .st0{fill:#FFFFFF;}
				.works .st1{font-family:'Lato-Bold';}
				.works .st2{font-size:14px;}
				.works .st3{font-family:'Lato-Medium';}
				.works .st4{fill:none;stroke:#000000;stroke-width:4;stroke-miterlimit:10;}
			</style>
			<g id="Layer_1">
			</g>
			<g id="Layer_7">
				<g id="Layer_8">
					<g class="works-1">
						<circle class="st0" cx="65.3" cy="33.1" r="6.1"/>
						<path d="M65.3,29c2.3,0,4.1,1.9,4.1,4.1c0,2.3-1.9,4.1-4.1,4.1s-4.1-1.9-4.1-4.1C61.1,30.9,63,29,65.3,29 M65.3,25
							c-4.5,0-8.1,3.6-8.1,8.1c0,4.5,3.6,8.1,8.1,8.1s8.1-3.6,8.1-8.1C73.4,28.6,69.8,25,65.3,25L65.3,25z"/>
					</g>
					<text class="works-1" transform="matrix(1 0 0 1 107.0215 37.1216)"><tspan x="0" y="0" class="st1 st2">UI/UX Designer &amp; Front End Developer</tspan><tspan x="0" y="24" class="st3 st2">Jacques Technology, DECO3800</tspan><tspan x="0" y="48" class="st3 st2">Feb - June 2018, Brisbane</tspan></text>
				</g>
				<g>
					<line class="st4 wl-1" x1="65" y1="40" x2="65" y2="133"/>
				</g>
				<g id="Layer_9">
					<g class="works-2">
						<circle class="st0" cx="65.5" cy="138" r="6.1"/>
						<path d="M65.5,133.9c2.3,0,4.1,1.9,4.1,4.1s-1.9,4.1-4.1,4.1s-4.1-1.9-4.1-4.1S63.2,133.9,65.5,133.9 M65.5,129.9
							c-4.5,0-8.1,3.6-8.1,8.1c0,4.5,3.6,8.1,8.1,8.1s8.1-3.6,8.1-8.1C73.6,133.5,70,129.9,65.5,129.9L65.5,129.9z"/>
					</g>
					<text class="works-2" transform="matrix(1 0 0 1 108.0215 143.1216)"><tspan x="0" y="0" class="st1 st2">UI/UX Designer &amp; Front End Developer</tspan><tspan x="0" y="24" class="st3 st2">Peentar Dev House</tspan><tspan x="0" y="48" class="st3 st2">Sept - Nov 2017, Jakarta</tspan></text>
					
				</g>
				<line class="st4 wl-2" x1="65" y1="145" x2="65" y2="232"/>
				<g id="Layer_10">
					<g class="works-3">
						<circle class="st0" cx="65.9" cy="237.9" r="6.1"/>
						<path d="M65.9,233.8c2.3,0,4.1,1.9,4.1,4.1s-1.9,4.1-4.1,4.1c-2.3,0-4.1-1.9-4.1-4.1S63.6,233.8,65.9,233.8 M65.9,229.8
							c-4.5,0-8.1,3.6-8.1,8.1c0,4.5,3.6,8.1,8.1,8.1c4.5,0,8.1-3.6,8.1-8.1C74,233.4,70.4,229.8,65.9,229.8L65.9,229.8z"/>
					</g>
					<text class="works-3" transform="matrix(1 0 0 1 109.0215 242.1216)"><tspan x="0" y="0" class="st1 st2">iOS Developer Intern</tspan><tspan x="0" y="24" class="st3 st2">Jojonomic Pte. Ltd.</tspan><tspan x="0" y="48" class="st3 st2">June - Aug 2017, Jakarta</tspan></text>
					
				</g>
			</g>
			</svg>



			<h5 class="skills-txt"> Skills </h5>
			<?xml version="1.0" encoding="utf-8"?>
			<!-- Generator: Adobe Illustrator 21.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
			<svg version="1.1" class="skills" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="400"
				 viewBox="0 0 450 330" style="enable-background:new 0 0 450 335;" xml:space="preserve">
			<style type="text/css">
				.skills .st0{fill:#FFFFFF;}
				.skills .st1{font-family:'Lato-Medium';}
				.skills .st2{font-size:14px;}
				.skills .st3{fill:none;stroke:#000000;stroke-width:4;stroke-miterlimit:10;}
			</style>
			<g id="Layer_1">
			</g>
			<g>
				<g id="skills-text-1">
					<g class="skills-1">
						<circle class="st0" cx="65.3" cy="33.1" r="6.1"/>
						<path d="M65.3,29c2.3,0,4.1,1.9,4.1,4.1s-1.9,4.1-4.1,4.1s-4.1-1.9-4.1-4.1S63,29,65.3,29 M65.3,25c-4.5,0-8.1,3.6-8.1,8.1
							s3.6,8.1,8.1,8.1s8.1-3.6,8.1-8.1S69.8,25,65.3,25L65.3,25z"/>
					</g>
					<text class="skills-1" transform="matrix(1 1.368330e-03 -1.368330e-03 1 107.1298 36.9973)"><tspan x="0" y="0" class="st1 st2">HTML5/CSS</tspan><tspan x="0" y="24" class="st1 st2">Javascript</tspan><tspan x="0" y="48" class="st1 st2">Jquery, Node.js, AngularJs</tspan><tspan x="0" y="72" class="st1 st2">Python</tspan><tspan x="0" y="96" class="st1 st2">Django</tspan><tspan x="0" y="120" class="st1 st2">Ruby on Rails</tspan><tspan x="0" y="144" class="st1 st2">Obj C</tspan></text>
				</g>
				<g>
					<line class="st3 sl-1" x1="65" y1="40" x2="65" y2="233"/>
				</g>
				<g id="skills-text-2">
					<g class="skills-2">
						<circle class="st0" cx="65.9" cy="237.9" r="6.1"/>
						<path d="M65.9,233.8c2.3,0,4.1,1.9,4.1,4.1c0,2.3-1.9,4.1-4.1,4.1c-2.3,0-4.1-1.9-4.1-4.1C61.7,235.6,63.6,233.8,65.9,233.8
							 M65.9,229.8c-4.5,0-8.1,3.6-8.1,8.1s3.6,8.1,8.1,8.1c4.5,0,8.1-3.6,8.1-8.1S70.4,229.8,65.9,229.8L65.9,229.8z"/>
					</g>
					<text class="skills-2" transform="matrix(1 1.368330e-03 -1.368330e-03 1 107.1298 244.9973)"><tspan x="0" y="0" class="st1 st2">Adobe Illustrator, Experience Design,</tspan><tspan x="0" y="24" class="st1 st2">Photoshop, Premiere</tspan><tspan x="0" y="48" class="st1 st2">Final Cut Pro</tspan><tspan x="0" y="72" class="st1 st2">Marvell app</tspan></text>
					
				</g>
			</g>
			</svg>


		</div>
	</div>
</div>

<script type="text/javascript" src="{% static 'js/about.js' %}"></script>

{% endblock %}

templates/application.html
<!DOCTYPE HTML>

<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">

	<title>{% block title %}{% endblock %}</title>

	<link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700,700i,900" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Lato:400,700,700i,900" rel="stylesheet">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

	<script src='http://cdnjs.cloudflare.com/ajax/libs/gsap/1.20.2/TweenLite.min.js'></script>
	<script src='http://cdnjs.cloudflare.com/ajax/libs/gsap/1.20.2/plugins/CSSPlugin.min.js'></script>

	<script src='http://cdnjs.cloudflare.com/ajax/libs/gsap/latest/TweenMax.min.js'></script>
	<script src='http://cdnjs.cloudflare.com/ajax/libs/sizzle/2.2.0/sizzle.js'></script>


	{% load static %}

	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<script type="text/javascript" src="{% static 'js/main.js' %}"></script>

</head>

<body>
	<div id="mainlayer2">
  		<h4>hello</h4>
  	</div>
	<svg width="100%" height="100%" id="mainlayer">
  		<rect width="100%" height="100%" style="fill:#1b2735" />
  	</svg>
  	

	<nav>
		<div class="logo" onclick="redirectTo('{% url 'homeTwo' %}')">
			<svg id="Layer_3" height="50" width="50" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 54.51 69.16"><defs>
			<style>.cls-1{fill:#1b2735;}.cls-2{font-size:63.15px;letter-spacing:-0.01em;}.cls-2,.cls-3{fill:#fff;font-family:PlayfairDisplay-Regular, Playfair Display;}.cls-3{font-size:13.73px;}.cls-4{letter-spacing:-0.02em;}</style></defs><title>asset-03</title><circle class="cls-1" cx="27.26" cy="33.17" r="27.26"/><text class="cls-2" transform="translate(2.48 53.93)">k</text><text class="cls-3" transform="translate(31.65 33.57)"><tspan class="cls-4">1</tspan><tspan x="4.85" y="0">3</tspan></text></svg>
		</div>

		<div class="normal">
			<ul>
				<li onclick="redirectTo('{% url 'homeTwo' %}')">HOME</li>
				<li onclick="redirectTo('{% url 'about' %}')">ABOUT</li>
				<li onclick="redirectTo('{% url 'works:workIndex' %}')">WORKS</li>
				<li onclick="redirectTo('{% url 'blog:blogs' %}')">BLOGS</li>
				<!-- <li>NOT WORK</li> -->
			</ul>
		</div>

		<div class="open">
			<span class="cls"></span>
			<span>
				<ul class="sub-menu">
					<li onclick="redirectTo('{% url 'homeTwo' %}')">HOME</a></li>
					<li onclick="redirectTo('{% url 'about' %}')">ABOUT</li>
					<li onclick="redirectTo('{% url 'works:workIndex' %}')">WORKS</li>
					<li onclick="redirectTo('{% url 'blog:blogs' %}')">BLOGS</li>
					<!-- <li>NOT WORK</li> -->
				</ul>
			</span>
			<span class="cls"></span>
		</div>	

	</nav>

  <div class="main-container" style="padding-bottom:30px;">
  	{% block content %}{% endblock %}
  </div>

  <div style="clear: both"></div>
	<footer id="footer-modif">Work of Keyne Oei. Mail me ! <a href="href="mailto:keynekassapa13@gmail.com"><i class="fas fa-envelope"></i></a> Follow me on
		<a href="http://www.behance.net/keynekassapa13" target="_blank">Behance,</a> 
		<a href="https://www.linkedin.com/in/keynekassapa/" target="_blank">Linkedin,</a>
		<a href="https://medium.com/@keynekassapa13/" target="_blank">Medium,</a>
		<a href="http://instagram.com/keynekassapa13/">Instagram</a>
		
	</footer>
	
</body>

</html>

templates/blogs/index.html
{% extends "application.html" %}

{% block title %}Blog - Keyne Oei{% endblock %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/blog.css' %}">

<div class="container">
<h1 class="text-bold page-title">Medium Blog</h1>

<div class="row" style="margin-top: 3%;">

	{% for eachblog in blogs %}
	<div class="col-sm-4">
		<a href="{{ eachblog.link }}" class="blog-attr" target="_blank">
		<div class="blog-box">
			<div class="datePub"> {{ eachblog.datePub }} </div>
			<h3> {{ eachblog.title }} </h3>
			<div class="content"> {{eachblog.content | safe |striptags| truncatewords:4}} </div>
		</div>
		</a>
	</div>
	
	{% endfor %}
</div>

</div>
<script type="text/javascript" src="{% static 'js/blog.js' %}"></script>

{% endblock %}

templates/works/detail.html
{% extends "application.html" %}

{% block title %}Works - Keyne Oei{% endblock %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/works.css' %}">
<style type="text/css">
	#footer-modif{
		position: initial !important; 
	}
</style>
<div class="container">
	<h1 class="text-bold page-title">{{ workname }}</h1>
	<div class="row">
		<div class="col-sm-6">
			{{ workcat }}
			<br/>
			See it in 
			<a href="{{workurl}}" target="_blank" class="work-link">behance!</a>
		</div>
		<div class="col-sm-6">
			{{ workdes }}
		</div>
	</div>
	<div class="work-detail-img">
		<img src="{{workpic}}" style="max-width: 100%" />
	</div>
</div>

<script type="text/javascript" src="{% static 'js/work-detail.js' %}"></script>
{% endblock %}

templates/works/index.html
{% extends "application.html" %}

{% block title %}Works - Keyne Oei{% endblock %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/works.css' %}">


<div class="container">
	<h1 class="text-bold page-title">Works</h1>	
	All the work is at <a href="http://www.behance.net/keynekassapa13" target="_blank" class="work-link"><i class="fab fa-behance-square"></i> Behance</a> 
	<div class="row">
		{% for i in works %}
		
		<div class="col-sm-4">
			<a href="{{i.b_id}}/">
			<div class="work-box" >
				<div class="work-box-bg" style="background-image: url('{{i.tumbn}}'); background-size: 100%;">
					
				</div>
				<div class="hover-show">
					<div class="content">
						<h4>{{ i.title| upper }}</h4>
						{{ i.category }}
					</div>
				</div>
			</div>
			</a>
		</div>
		
		{% endfor %}
	</div>

</div>

<script type="text/javascript" src="{% static 'js/work.js' %}"></script>

{% endblock %}